---
# tasks file for aem

- name: Copy AEM 6.1 jar file
  copy:
    src: "{{ aem.jarfile }}"
    dest: /tmp/aem61.jar
    mode: 0644
    force: no

- name: Create group
  group:
    name: "{{ aem.instance.group }}"
    state: present

- name: Create user
  user:
    name: "{{ aem.instance.user }}"
    group: "{{ aem.instance.group }}"

- name: Create AEM directory
  file:
    path: "{{ aem.instance.base }}/{{ aem.instance.name }}"
    owner: "{{ aem.instance.user }}"
    group: "{{ aem.instance.group }}"
    state: directory
    mode: 0755

- name: Unpack the Jar
  become: yes
  become_user: "{{ aem.instance.user }}"
  command: "java -jar /tmp/aem61.jar -b {{ aem.instance.base }}/{{ aem.instance.name }} -unpack"
  args:
    creates: "{{ aem.instance.base }}/{{ aem.instance.name }}/crx-quickstart/readme.txt"

- name: Create the AEM license file
  template:
    src: "{{ aem.templates.license }}"
    dest: "{{ aem.instance.base }}/{{ aem.instance.name }}/license.properties"
    owner: "{{ aem.instance.user }}"
    group: "{{ aem.instance.group }}"
    mode: 0755
    force: no
  notify:
    - restart aem-{{ aem.instance.name }}

- name: Create the AEM start file
  template:
    src: "{{ aem.templates.start }}"
    dest: "{{ aem.instance.base }}/{{ aem.instance.name }}/crx-quickstart/bin/start"
    owner: "{{ aem.instance.user }}"
    group: "{{ aem.instance.group }}"
    mode: 0755
  notify:
    - restart aem-{{ aem.instance.name }}

- name: Create init.d file
  template:
    src: "{{ aem.templates.init }}"
    dest: "/etc/init.d/aem-{{ aem.instance.name }}"
    owner: root
    group: root
    mode: 0755

- name: Install packages
  copy:
    src: "files/packages/{{ item }}"
    dest: "{{ aem.instance.base }}/{{ aem.instance.name }}/crx-quickstart/install/{{ item }}"
    owner: "{{ aem.instance.user }}"
    group: "{{ aem.instance.group }}"
    mode: 0644
    force: no
  with_items: "{{ aem.install.packages }}"
  notify:
    - restart aem-{{ aem.instance.name }}

- name: "Create aem-{{ aem.instance.name }} service"
  service:
    name: "aem-{{ aem.instance.name }}"
    enabled: yes
    state: started
    sleep: 10
